### ISSUE TITLE
Querying of values is not enough

### ISSUE THREAD

**Issue by jcelerier** [Vidvox/OSCQueryProposal#29]
Hello,

I think that there is a small problem in the third example : 

```
http://ip:port/foo?VALUE
  {
      "VALUE": [
          0.5
      ]
  }
```

How is the server expected to answer if the parameter has OSC value-less types (i.e. bool ("T/F") / nil ("N") in OSC) ? I think that putting the `TYPE` in the answer would be necessary in this case. Or we could have a small duplication of data, and also put the bool / null value in the `VALUE` list of elements since JSON happens to have support for these two types (what I did for now).

Ideas ?

Some other points : 
- Should oscquery only cover the "base" type tags or most / all of them ? 
- For the transfer of generic, osc-blob like data, I think that they should be encoded in some json-friendly encoding like base64 (I did this for now but just put it in a string hence this is ambiguous without the `TYPE` argument) or base85.
- Shouldn't the oscquery client / server have support for gzipped encoding in case of very big namespaces ?
- A corner case with listening :
  Suppose that the server has an address `/a` with a `[1, "blah"]` value and ranges for both values.
  Now, the server sometimes send updated values with the same type / range.

But what is supposed to happen if for some reason, the client receives a message with the wrong type or wrong number of arguments ? Is it supposed to : 
- discard the message ? (I did this for now)
- adapt its own state with the new information ? This poses the problem that all information of range / clipmode would be lost since it depends on the number of values present, and they would have to be reverted to default values.

**Comment by lov** [comment]
Hi,

> How is the server expected to answer if the parameter has OSC value-less types...

I think `http://ip:port/foo?VALUE` is practically called after you `http://ip:port` or even `http://ip:port/foo` so basically you know the type of the address when you ask its value, so if it reports nil or T/F you it should not be a problem in my opinion.

> Should oscquery only cover the "base" type tags or most / all of them.

Good question! I'd suggest that the "minimal" implementation (https://github.com/mrRay/OSCQueryProposal/issues/25) should cover only the base type tags.

> Shouldn't the oscquery client / server have support for gzipped encoding in case of very big namespaces?

Hm, I think what could be sometimes huge in amount of the data is the full namespace discovery, but I guess we don't need to call that too frequent, right? PATH_CHANGED could be useful here, or even giving an option on user-side to re-discover the whole thing. 

> But what is supposed to happen if for some reason, the client receives a message with the wrong type or wrong number of arguments?

I would just discard that, because that is the safest thing you can do, at least in my opinion.

**Comment by jcelerier** [comment]
> I'd suggest that the "minimal" implementation (#25) should cover only the base type tags.

Seems pretty sensible. Do you think that there should be a standard way for a given implementation to expose its capabilities ? Or would it just be on the basis of "ignore what is not understood".

> Hm, I think what could be sometimes huge in amount of the data is the full namespace discovery, but I guess we don't need to call that too frequent, right? 

I was also thinking of aggregating all the listened values of a client to send them if they are numerous. For instance, if an application has a 3D scene with 500 objects that all have x, y, z properties plus other stuff, and if these objects all move at some tick rate, it might be more interesting to send a single big tcp packet with all the `VALUES` than 1500+ UDP messages, if there is some client listening to everything.

> PATH_CHANGED could be useful here, or even giving an option on user-side to re-discover the whole thing.

Yep.

> I would just discard that, because that is the safest thing you can do, at least in my opinion.

Arighty then.

Thanks!

**Comment by lov** [comment]
> ... Or would it just be on the basis of "ignore what is not understood".

I think this is the right approach - if a client cannot understand that, just simply ignore it.

> if an application has a 3D scene with 500 objects that all have x, y, z properties plus other stuff, and if these objects all move at some tick rate, it might be more interesting to send a single big tcp packet with all the `VALUES` than 1500+ UDP messages...

Yeah, but that is basically streaming aka OSC over TCP not related to namespace discovery and in my opinion (https://github.com/mrRay/OSCQueryProposal/issues/25) that should not be the part of this proposal at the first place. Could be a nice and great addition, but application that already supports OSC over UDP namespace discovery is the most important part (at least for me), and I would be surprised if devs gonna replace their working-for-years libraries to something new (although it would be nice to handle everything within one library and protocol). Just my 2 cents.

**Comment by mrRay** [comment]
i'm closing this issue because i think that the issues it discusses have been addressed.  the proposal now includes a table that defines which JSON data types are to be used for each OSC data type.  OSC blobs (and midi and nil and infinity) are all "nil".

if there are any additional concerns, please feel free to re-open this issue or create another one!
