### ISSUE TITLE
OSC client info

### ISSUE THREAD

**Issue by lov** [Vidvox/OSCQueryProposal#31]
I think it would be useful to pass the OSC server's name and port too with the root node, so apps using the Query protocol may know which OSC server corresponds to the OSC Query server. I'm thinking something like `OSCCLIENT_NAME`, `OSCCLIENT_IP` and `OSCCLIENT_PORT`

**Comment by jcelerier** [comment]
How would the "IP" part work behind a NAT ?

**Comment by lov** [comment]
> How would the "IP" part work behind a NAT ?

Nice catch! Yeah, we probably won't need that.

**Comment by jcelerier** [comment]
or maybe directly go into the future and require an ipv6, since most won't be behind NATs :p

**Comment by mrRay** [comment]
i added a basic HOST_INFO attribute that would partially address this [here](https://github.com/mrRay/OSCQueryProposal/commit/f7f4c505e72895f6fd12644dd67aa587a0fd9445), please look it over and let me know if there are any modifications you'd like to see to it...

**Comment by jcelerier** [comment]
rethinking of it, I think that `OSCCLIENT_IP` (or maybe `OSCCLIENT_HOST` which could be more generic ?) would still be important to have.

For instance, if an oscquery server advertises an OSC client which is on another computer.

**Comment by lov** [comment]
Yes, this is a cool idea. We could make a recommendation/best practise to use the same port too for OSC, so if there is an OSC server at localhost:3333 (UDP) then the best if the OSCQuery server is on the same port and address, so this case it would be localhost:3333 (TCP).

How does this sound?

**Comment by jcelerier** [comment]
sounds good !

**Comment by mrRay** [comment]
i'm closing this issue because i think the current state of the proposal addresses most of these concerns.  specifically, the proposal includes OSC_IP and OSC_PORT, but the proposal also explicitly declares that if these are absent the assumption is that clients should use the same IP/port as the query server.

if there are any additional concerns on this topic or you feel that i missed anything, please feel free to re-open this issue or create another!
