### ISSUE TITLE
vectors syntax

### ISSUE THREAD

**Issue by bltzr** [Vidvox/OSCQueryProposal#50]
Currently, the syntax for vectors seems unsufficiently defined: ie. in most implementations I reviewed, e.g. a 2D position vector would be expressed in this way:
```
"my2Dpos" : {
              "DESCRIPTION" : "2d Position my2Dpos",
              "FULL_PATH" : "\/OSCQUERY\/Control Surface 1\/my2Dpos",
              "RANGE" : [
                {
                  "MAX" : 1,
                  "MIN" : 0
                },
                {
                  "MAX" : 1,
                  "MIN" : 0
                }
              ],
              "TYPE" : "ff",
              "VALUE" : [
                0.46330180764198303,
                0.27508223056793213
              ]
            }
 },
```
(this is coming from VDMX)

In se, there's no deep problem with that, it works.

Although, after reading @mrRay's proposal to implement arrays for catering with colors in:
https://github.com/Vidvox/OSCQueryProposal/issues/47#issuecomment-410844739

I was wondering if it wouldn't be more appropriate to use OSC arrays to express the fact that those are not just 2 individual float values, but a vector of floats, expressing a 2D position. That is strongly related to the matters discussed in #38 , but more on that later.

So, if we followed  @mrRay's reasoning in the above-linked issue, this 2D position would be more adequately expressed in this way, IMHO:

```
"my2Dpos" : {
              "DESCRIPTION" : "2d Position my2Dpos",
              "FULL_PATH" : "\/OSCQUERY\/Control Surface 1\/my2Dpos",
              "RANGE" : [
              [
                {
                  "MAX" : 1,
                  "MIN" : 0
                },
                {
                  "MAX" : 1,
                  "MIN" : 0
                }
              ]
              ],
              "TYPE" : "[ff]",
              "VALUE" : [
                [
                0.46330180764198303,
                0.27508223056793213
                ]
             ]
            }
          },
```

Notice that the type is no longer "ff", but has become "[ff]", as it's allowed (even maybe recommended, as this is an array, and not just a pair of floats) by the OSC 1.0 specs.

That might sound like nitpicking, by just adding two extraneous braces that don't look so good. 
But, what if we wanted to include this 2D position vector into a tuple ? If we don't use those extra braces, then we would lose the information about those two floats being part of the same entity (or quantity, to talk in physics-jargon).

Of course, this is an incremental change proposal, so if we implement this, we will still be able to support 2 positions (for instance) expressed as a pair of floats, and not as a vector (or array). But this extra info helps making the fact that it's a vector clear and unambiguous.

Now, I can go back to talking **UNIT**s in #38 with this proposal in mind.

**Comment by mrRay** [comment]
> "If we don't use those extra braces, then we would lose the information about those two floats being part of the same entity"

hmmm...*are* they part of the same entity?  if we think of an OSC message as an RPC, then they're just two arguments passed to the same function, instead of two adjacent members in a struct.  it's like calling `PassPointCoords(float x, float y)`.  while you could certainly construct a 2d point from the passed values, is it accurate to say that you're passing a 2d point?

even if you put them in a simple c-style array, does that make it a "2d point"?  is this a 2d point, or is this just an array with two values?

`float		a[] = { 0., 0. };`

while you can certainly create a point from these values/from the contents of this array, i've got a hard time saying that an array of two floats "is a point".

i *don't* have a problem defining this as a 2d point:

`struct 2DPoint { float	x,y; };`

what is the process for making a definition like that within the confines of the OSC encoding?  i don't think there is one right now- if i'm understanding you correctly, it sounds like you're suggesting we use the array types to designate ad-hoc data types?

the array types explicitly designate arrays- i don't know how other people use them in OSC, but from a purely linguistic standpoint it seems odd to use them to define a complex data type.  while it's true that an array is "a collection of stuff", it's also true that as "a collection of stuff" an array is an explicit and well-defined type.  if it's an array, it's *not* a complex data type.

i don't have any answers right now, folks- and like @jcelerier observed in another thread, it sounds a bit like this is trying to establish an object model/programming language on top of OSC, which is a tall order and a bit beyond the scope of this proposal.

theoretical debates aside, seeing as how pretty much everybody is already using "ff" to send 2d point coordinates, wouldn't changes like this to long-standing OSC conventions cause more conflicts and incompatibilities than just going with the flow?

**Comment by bltzr** [comment]
thanks for your insights, @mrRay 

actually my proposal really makes sense when a vec is part of a tuple, which I guess is a very rare (even unexisting) edge case, so maybe we shouldn't worry too much about it

also, I think the change you made to the proposal:
> If all of the elements of one of these optional attribute share the same value, it's acceptable to only list a single value (which clients will assume corresponds to all of the elements) for the sake of brevity.

is really smart and helps solving (most of) this issue in a very elegant way

I'll look into the ```vectors.md``` file again (but maybe not today, I'll have to leave home soon) and see if I can modify it accordingly, and also based on your other remarks

**Comment by bltzr** [comment]
> hmmm...are they part of the same entity?

epistemologically speaking, I'd say: yes.

but we're not dealing with Philosophy of science here, but with actual software implementations, so I guess the most sensible attitude is the one you suggest, aka:
> wouldn't changes like this to long-standing OSC conventions cause more conflicts and incompatibilities than just going with the flow?

**Comment by bltzr** [comment]
So I guess I can close this one
